import type { Metadata } from "next";
import "./globals.css";
import { RootLayout as _RootLayout } from "@/components/layouts/root";
import { inter } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={`${inter.className} h-full antialiased`}>
        <_RootLayout>
          {children}
        </_RootLayout>
      </body>

    </html>
  );
}
