import type { Metadata } from "next"
import "./globals.css"
import { RootLayout as _RootLayout } from "@/components/layouts/root"
import { poppins } from "@/lib/fonts"
import { Geist } from "next/font/google"
import { cn } from "@/lib/utils"

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={cn("font-sans", geist.variable)}>
      <body
        className={`${poppins.className} h-full min-h-screen bg-[#F0F2F5] antialiased dark:bg-[#232E42]`}
      >
        <_RootLayout>{children}</_RootLayout>
      </body>
    </html>
  )
}
